apiVersion: v1
kind: Service
metadata:
  name: nginx-host
spec:
  selector: 
    app: story
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
      nodePort: 30006

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-host
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      volumes:
        - name: nginx-host
          persistentVolumeClaim:
            claimName: nginx-host

      initContainers:
        - name: copy-nginx-content
          image: nginx
          command: ["/bin/sh", "-c"]
          args:
            - cp -r /usr/share/nginx/html/* /mnt/html/
          volumeMounts:
            - name: nginx-host
              mountPath: /mnt/html

      containers:
        - name: story
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx-host
