apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-host
spec:
  volumeName: nginx-host
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests: 
      storage: 500Mi