apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: my-nginx-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: maheshbharambe45/flask_app:latest
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: my-svc
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
   - port: 5000
     targetPort: 5000
     

