apiVersion: v1
kind: Pod
metadata:
  name: mypod12
  labels:
    app: nginx   
spec:
  containers:
    - image: nginx:latest
      name: my-container
      ports:
        - containerPort: 80
      env:
        - name: USERNAME
          valueFrom:
            configMapKeyRef:
              name: demo-cf
              key: NAME
              
        - name: ID
          valueFrom:
            configMapKeyRef:
              name: demo-cf
              key: ID
        
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: pass
            