apiVersion: v1
kind: Pod
metadata:
  name : my-pod
  labels:
    app: flask
spec:
  containers:
    - image: maheshbharambe45/flask_app:latest
      name: my-flask-cont
      ports:
        - containerPort: 5000
      envFrom:
        - configMapRef:
            name: demo-cf