apiVersion: v1 
kind: ReplicationController 
metadata:
  name: my-rc
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: my-container-1
          image: nginx:latest
          ports:
            - containerPort: 80