apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demoreplicaset
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: my-ct
          image: nginx:latest
          ports:
            - containerPort: 80 