apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-dep
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      name: nginx-cont
      labels:
        app: demo 
    spec:
      containers:
        - name: nginx-cont
          image: nginx:latest
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: svc-dep 
spec:
  type: NodePort
  selector:
    app: demo
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30005