apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: demo 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: nginx-cont
          image: nginx:latest
          ports:
            - containerPort: 80
  
  