apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: python-sql-demo
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort 
