apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-rc
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    app: demo
  template:
    metadata:
      name: nginx-pod
      labels:
        app: demo
    spec:
      containers:
        - name: nginx-demo
          image: nginx:latest
          ports:
            - containerPort: 80
