apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-rc
  labels:
    app: rc
spec:
  replicas: 2
  selector:
    app: rc
  template:
    metadata:
      labels:
        app: rc
    spec:
      containers:
        - name: nginx-cont
          image: nginx:latest
          ports:
            - containerPort: 80
