apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: demo-rs
  labels:
    app: rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rs
  template:
    metadata:
      name: nginx-rc
      labels:
        app: rs
    spec:
      containers:
        - name: nginx-cont
          image: nginx:latest
          ports:
            - containerPort: 80
