apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: app-container
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: log-agent
      image: busybox:1.36
      command: ["sh", "-c", "while true; do echo 'Logging...'; sleep 5; done"]
