apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  labels:
    app: demo
spec:
  containers:
    - name: my-cont
      image: nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: NAME
          value: "BHAGYA"