apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: test
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      name: demo-pod
      labels:
        app: demo
    spec: 
      containers:
        - name: nginx-cont
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name : USERNAME
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: username

            - name : PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: password                

                  