---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  ID: IkFBQ0hBTCIgDQo=
  PASS: Ik1BSEVTSEA5MDY3IiANCg==
  GREET: QllFCg==

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: my-cont1
      image: nginx:latest
      envFrom:
        - secretRef:
            name: my-secret